require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dashboard/workspaces", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Workspace. As you add validations to Workspace, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Engineering", feature_set: "personal" }
  }

  let(:invalid_attributes) {
    { name: "" }
  }

  let!(:user) {
    create(:user)
  }

  before do
    sign_in user
  end

  def create_workspace(attributes = valid_attributes)
    Workspace.create!(attributes).tap { |workspace| workspace.users << user }
  end

  describe "GET /index" do
    it "renders a successful response" do
      create_workspace
      get dashboard_workspaces_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      workspace = create_workspace
      get dashboard_workspace_url(workspace)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dashboard_workspace_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      workspace = create_workspace
      get edit_dashboard_workspace_url(workspace)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Workspace" do
        expect {
          post dashboard_workspaces_url, params: { workspace: valid_attributes }
        }.to change(Workspace, :count).by(1)
      end

      it "redirects to the created workspace" do
        post dashboard_workspaces_url, params: { workspace: valid_attributes }
        expect(response).to redirect_to(dashboard_workspace_url(Workspace.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Workspace" do
        expect {
          post dashboard_workspaces_url, params: { workspace: invalid_attributes }
        }.to change(Workspace, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post dashboard_workspaces_url, params: { workspace: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Renamed Workspace" }
      }

      it "updates the requested workspace" do
        workspace = create_workspace
        patch dashboard_workspace_url(workspace), params: { workspace: new_attributes }
        workspace.reload
        expect(workspace.name).to eq("Renamed Workspace")
      end

      it "redirects to the workspace" do
        workspace = create_workspace
        patch dashboard_workspace_url(workspace), params: { workspace: new_attributes }
        workspace.reload
        expect(response).to redirect_to(dashboard_workspace_url(workspace))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        workspace = create_workspace
        patch dashboard_workspace_url(workspace), params: { workspace: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested workspace" do
      workspace = create_workspace
      expect {
        delete dashboard_workspace_url(workspace)
      }.to change(Workspace, :count).by(-1)
    end

    it "redirects to the workspaces list" do
      workspace = create_workspace
      delete dashboard_workspace_url(workspace)
      expect(response).to redirect_to(dashboard_workspaces_url)
    end
  end
end
